#!/usr/bin/env node

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import ts from 'typescript';

const DEFAULT_SOURCE = 'http://localhost:9080/yksilo/openapi/openapi.json/Yksilo';
const OUT_FILE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'src/api/schema.d.ts');

const source = process.argv[2] ?? process.env.OPENAPI_URL ?? DEFAULT_SOURCE;

const BLOB = ts.factory.createTypeReferenceNode(ts.factory.createIdentifier('Blob'));

const ast = await openapiTS(/^https?:/.test(source) ? new URL(source) : new URL(source, import.meta.url), {
  transform(schemaObject) {
    if (schemaObject.format === 'binary' && (schemaObject.type === 'string' || !schemaObject.type)) {
      return schemaObject.nullable
        ? ts.factory.createUnionTypeNode([BLOB, ts.factory.createLiteralTypeNode(ts.factory.createNull())])
        : BLOB;
    }
  },
});

await fs.writeFile(OUT_FILE, ['/**\n * This file was auto-generated by openapi-typescript.\n*/\n\n', astToString(ast)]);
